name: 'Example'
author: "Hyunbin Park"
description: 'Check if my custom action works'
inputs:
  something:  # id of input
    description: "I don't know what this is"
    required: false
    default: '1'
outputs:
  random-number:  # id of output
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
